import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, APP_VERSION } from './config.js';
import { setupUpdates } from './update.js';
import { setupInstall } from './install.js';

const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null, profile=null;
const canCreate=()=>['creator','admin'].includes(profile?.role), canApprove=()=>['approver','admin'].includes(profile?.role), isAdmin=()=>profile?.role==='admin';

setupUpdates();
setupInstall();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.warn);

function note(msg){const el=$('#auth-note');el.textContent=msg;el.classList.remove('hidden')}
function clearNote(){$('#auth-note').classList.add('hidden')}
function setAuthMode(mode){const login=mode==='login';$('#login-form').classList.toggle('hidden',!login);$('#signup-form').classList.toggle('hidden',login);$('#auth-login-tab').className=login?'maroon':'ghost';$('#auth-signup-tab').className=login?'ghost':'maroon';clearNote()}
async function signInGoogle(){clearNote();const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)note(error.message)}
async function signInEmail(e){e.preventDefault();clearNote();const f=new FormData(e.currentTarget);const email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');const {error}=await db.auth.signInWithPassword({email,password});if(error)return note('Email/password sign-in failed. Check your email and password. If this address was originally registered with Google, use Continue with Google.');location.reload()}
async function signUpEmail(e){e.preventDefault();clearNote();const form=e.currentTarget,submit=form.querySelector('button[type="submit"]'),originalText=submit?.textContent;const f=new FormData(form);const full_name=String(f.get('full_name')||'').trim(),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');if(full_name.length<2)return note('Please enter your full name.');if(password.length<10)return note('Use a password with at least 10 characters.');if(submit){submit.disabled=true;submit.textContent='Creating account…'}try{const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name}}});if(error){if(/already registered/i.test(error.message))return note('An account already exists with this email. Please sign in instead, or use Continue with Google if that is how the account was created.');return note(`Account could not be created: ${error.message}`)}if(data.session){note('Account created successfully. Signing you in…');setTimeout(()=>location.reload(),500);return}note('Account request completed, but no sign-in session was returned. Please try signing in.');setAuthMode('login');}finally{if(submit){submit.disabled=false;submit.textContent=originalText||'Create account'}}}
async function forgotPassword(){clearNote();const email=String(new FormData($('#login-form')).get('email')||'').trim();if(!email)return note('Enter your email address first.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return note(error.message);note('Password reset request received. Check your inbox and spam folder.')}
async function signOut(){await db.auth.signOut();location.reload()}
async function loadProfile(){const {data,error}=await db.from('profiles').select('id,full_name,role,is_active').eq('id',user.id).single();if(error)throw error;profile=data;if(!profile.is_active)throw new Error('This account has been disabled by an administrator.');}
function paintIdentity(){const meta=user.user_metadata||{};$('#who-name').textContent=profile.full_name||meta.full_name||meta.name||'Signed in';$('#who-email').textContent=user.email||'';$('#who-role').textContent=profile.role;$('#who').classList.remove('hidden');$('#tab-create').classList.toggle('hidden',!canCreate());$('#tab-admin').classList.toggle('hidden',!(canApprove()||isAdmin()));}
function statusClass(s){return ['active','located'].includes(s)?'active':s==='pending'?'pending':'closed'}
function alertCard(a,admin=false){const controls=admin&&canApprove()&&a.status==='pending'?`<button class="maroon" data-approve="${a.id}">Approve & activate</button>`:'';const close=admin&&canApprove()&&['active','located'].includes(a.status)?`<button class="ghost" data-close="${a.id}">Child located / all clear</button>`:'';return `<article class="card alert"><div class="row between"><h3>${esc(a.title||'Community Assistance Request')}</h3><span class="status ${statusClass(a.status)}">${esc(a.status)}</span></div>${a.photo_url?`<img src="${esc(a.photo_url)}" alt="Alert" style="max-width:100%;max-height:320px;border-radius:12px">`:''}<p><strong>${esc(a.child_name||'')}</strong>${a.age?` · Age ${esc(a.age)}`:''}</p><p>${esc(a.description)}</p>${a.last_known?`<p><strong>Last known:</strong> ${esc(a.last_known)}</p>`:''}${a.vehicle?`<p><strong>Vehicle/info:</strong> ${esc(a.vehicle)}</p>`:''}${a.law_agency?`<p><strong>Investigating agency:</strong> ${esc(a.law_agency)}</p>`:''}${a.law_phone?`<p><strong>Information:</strong> <a href="tel:${esc(a.law_phone)}">${esc(a.law_phone)}</a></p>`:''}<div class="row">${controls}${close}</div></article>`}
async function loadAlerts(){const {data,error}=await db.from('alerts').select('*').in('status',['active','located','closed']).order('created_at',{ascending:false}).limit(50);if(error)throw error;$('#alerts').innerHTML=data.length?data.map(a=>alertCard(a)).join(''):'<div class="card"><h3>No active alerts</h3><p class="mut">There are no approved community assistance alerts right now.</p></div>';}
async function loadAdmin(){if(!(canApprove()||isAdmin()))return;const {data,error}=await db.from('alerts').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;$('#pending').innerHTML=`<div class="card"><h3>District alert console</h3><p class="mut">Pending requests require an approver or administrator.</p></div>`+data.map(a=>alertCard(a,true)).join('');if(isAdmin())await loadUsers();}
async function loadUsers(){const {data,error}=await db.from('profiles').select('id,full_name,role,is_active,created_at').order('created_at',{ascending:false});if(error)throw error;$('#users').innerHTML=`<div class="card"><h3>Authorized users</h3><p class="mut">Administrators can change roles or revoke access. Revoked users lose database access immediately, even if an old sign-in session remains on their device.</p>${data.map(p=>{const self=p.id===user.id;return `<div class="row between user-row"><div class="user-info"><strong>${esc(p.full_name||p.id.slice(0,8))}</strong><br><span class="user-state ${p.is_active?'':'revoked'}">${p.is_active?'Active':'Access revoked'}</span></div><div class="row user-actions"><select data-role="${p.id}" ${p.is_active?'':'disabled'}><option ${p.role==='community'?'selected':''}>community</option><option ${p.role==='creator'?'selected':''}>creator</option><option ${p.role==='approver'?'selected':''}>approver</option><option ${p.role==='admin'?'selected':''}>admin</option></select><button class="ghost" data-save-role="${p.id}" ${p.is_active?'':'disabled'}>Save role</button><button class="${p.is_active?'danger':'maroon'}" data-access="${p.id}" data-active="${p.is_active?'1':'0'}" ${self?'disabled title="You cannot revoke your own admin access here."':''}>${p.is_active?'Revoke access':'Restore access'}</button></div></div>`}).join('')}</div>`}
async function createAlert(e){e.preventDefault();const f=new FormData(e.currentTarget), payload=Object.fromEntries([...f.entries()].map(([k,v])=>[k,String(v).trim()||null]));payload.title='Community Assistance Request';payload.created_by=user.id;payload.status='pending';payload.is_public=false;const {error}=await db.from('alerts').insert(payload);if(error)return alert(error.message);e.currentTarget.reset();alert('Submitted for approval.');await loadAdmin();}
async function approve(id){const {error}=await db.from('alerts').update({status:'active',is_public:true,approved_by:user.id,approved_at:new Date().toISOString()}).eq('id',id).eq('status','pending');if(error)return alert(error.message);await Promise.all([loadAdmin(),loadAlerts()]);}
async function closeAlert(id){const {error}=await db.from('alerts').update({status:'closed',is_public:true,closed_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await Promise.all([loadAdmin(),loadAlerts()]);}
async function saveRole(id,button){const select=document.querySelector(`[data-role="${id}"]`);const {error}=await db.from('profiles').update({role:select.value}).eq('id',id);if(error)return alert(error.message);button.textContent='Saved';setTimeout(()=>button.textContent='Save role',1200);}
async function toggleAccess(id,button){if(id===user.id)return alert('You cannot revoke your own admin access from this screen.');const active=button.dataset.active==='1',next=!active,verb=next?'restore access for':'revoke access for';if(!confirm(`Are you sure you want to ${verb} this user?`))return;button.disabled=true;const {error}=await db.from('profiles').update({is_active:next}).eq('id',id);if(error){button.disabled=false;return alert(error.message)}await loadUsers();}
function tab(name){for(const n of ['feed','create','admin']){$('#'+n).classList.toggle('hidden',n!==name);$('#tab-'+n)?.classList.toggle('on',n===name)}if(name==='admin')loadAdmin().catch(e=>alert(e.message));}
async function verifyAccess(){if(!user)return;const {data,error}=await db.from('profiles').select('is_active').eq('id',user.id).single();if(error||!data?.is_active){await db.auth.signOut({scope:'local'}).catch(()=>{});location.reload();}}
async function boot(){console.log(`BSD #7 Community Assistance v${APP_VERSION}`);const versionEl=$('#app-version');if(versionEl)versionEl.textContent=`v${APP_VERSION}`;const {data:{session}}=await db.auth.getSession();if(!session)return;user=session.user;try{await loadProfile()}catch(e){await db.auth.signOut({scope:'local'}).catch(()=>{});return note(e.message)}$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');paintIdentity();await loadAlerts();}
$('#google').onclick=signInGoogle;$('#auth-login-tab').onclick=()=>setAuthMode('login');$('#auth-signup-tab').onclick=()=>setAuthMode('signup');$('#login-form').onsubmit=signInEmail;$('#signup-form').onsubmit=signUpEmail;$('#forgot-password').onclick=forgotPassword;$('#signout').onclick=signOut;$('#refresh').onclick=()=>loadAlerts().catch(e=>alert(e.message));$('#alert-form').onsubmit=createAlert;$('#tab-feed').onclick=()=>tab('feed');$('#tab-create').onclick=()=>tab('create');$('#tab-admin').onclick=()=>tab('admin');document.addEventListener('click',e=>{const a=e.target.closest('[data-approve]');if(a)approve(a.dataset.approve);const c=e.target.closest('[data-close]');if(c)closeAlert(c.dataset.close);const r=e.target.closest('[data-save-role]');if(r)saveRole(r.dataset.saveRole,r);const x=e.target.closest('[data-access]');if(x)toggleAccess(x.dataset.access,x)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)verifyAccess().catch(()=>{})});window.addEventListener('focus',()=>verifyAccess().catch(()=>{}));db.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'&&!user)boot();});boot().catch(e=>{console.error(e);note(e.message)});
